/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertFailed: typeof import('./src/components/alerts/AlertFailed.vue')['default']
    AlertStatus: typeof import('./src/components/AlertStatus.vue')['default']
    AlertStatusUpdate: typeof import('./src/components/AlertStatusUpdate.vue')['default']
    AlertSuccess: typeof import('./src/components/alerts/AlertSuccess.vue')['default']
    CheckBoxComplete: typeof import('./src/components/tasks/checkboxes/CheckBoxComplete.vue')['default']
    CheckBoxItem: typeof import('./src/components/tasks/checkboxes/CheckBoxItem.vue')['default']
    CheckBoxUncomplete: typeof import('./src/components/tasks/checkboxes/CheckBoxUncomplete.vue')['default']
    CircleBackground: typeof import('./src/components/404/CircleBackground.vue')['default']
    CircleButton: typeof import('./src/components/tasks/buttons/CircleButton.vue')['default']
    EditSpecificTask: typeof import('./src/components/tasks/EditSpecificTask.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ErrorComponent: typeof import('./src/components/tasks/ErrorComponent.vue')['default']
    ErrorItem: typeof import('./src/components/tasks/ErrorItem.vue')['default']
    FormDescription: typeof import('./src/components/tasks/FormDescription.vue')['default']
    IconArrowDown: typeof import('./src/components/icons/IconArrowDown.vue')['default']
    IconBox: typeof import('./src/components/icons/IconBox.vue')['default']
    IconBurger: typeof import('./src/components/icons/IconBurger.vue')['default']
    IconCheck: typeof import('./src/components/icons/IconCheck.vue')['default']
    IconCircleCheck: typeof import('./src/components/icons/IconCircleCheck.vue')['default']
    IconClock: typeof import('./src/components/icons/IconClock.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconExclaimationTriangle: typeof import('./src/components/icons/IconExclaimationTriangle.vue')['default']
    IconSchedule: typeof import('./src/components/icons/IconSchedule.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconXMark: typeof import('./src/components/icons/IconXMark.vue')['default']
    InputDate: typeof import('./src/components/tasks/inputs/InputDate.vue')['default']
    InputDescription: typeof import('./src/components/tasks/inputs/InputDescription.vue')['default']
    InputFile: typeof import('./src/components/tasks/InputFile.vue')['default']
    InputTask: typeof import('./src/components/tasks/InputTask.vue')['default']
    InputTitle: typeof import('./src/components/tasks/inputs/InputTitle.vue')['default']
    LoadingItem: typeof import('./src/components/tasks/LoadingItem.vue')['default']
    Modal: typeof import('./src/components/tasks/modal/Modal.vue')['default']
    NoItem: typeof import('./src/components/tasks/NoItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchItem: typeof import('./src/components/tasks/search/SearchItem.vue')['default']
    SelectPriority: typeof import('./src/components/tasks/selects/SelectPriority.vue')['default']
    SelectTaskStatus: typeof import('./src/components/tasks/selects/SelectTaskStatus.vue')['default']
    ShowDate: typeof import('./src/components/tasks/dates/ShowDate.vue')['default']
    ShowDateInEditTask: typeof import('./src/components/tasks/dates/ShowDateInEditTask.vue')['default']
    SkeletonLoading: typeof import('./src/components/loading/SkeletonLoading.vue')['default']
    SmallButton: typeof import('./src/components/tasks/buttons/SmallButton.vue')['default']
    StatusPriorityItem: typeof import('./src/components/tasks/StatusPriorityItem.vue')['default']
    TaskItem: typeof import('./src/components/tasks/TaskItem.vue')['default']
    TaskList: typeof import('./src/components/tasks/TaskList.vue')['default']
  }
}
